use axum::{routing::get, Json, Router};
use utoipa::{
    openapi::security::{HttpAuthScheme, HttpBuilder, SecurityScheme},
    Modify, OpenApi,
};

use crate::state::AppState;

#[derive(OpenApi)]
#[openapi(
    info(
        title = "produktive API",
        version = "0.1.0",
        description = "Uptime tracker API. Per-user workspaces, monitors (HTTP/TCP/Ping), and TimescaleDB-backed checks."
    ),
    paths(
        crate::http::health::health,
        crate::auth::routes::register,
        crate::auth::routes::login,
        crate::auth::routes::forgot_password,
        crate::auth::routes::reset_password,
        crate::auth::routes::auth_config,
        crate::auth::routes::github_start,
        crate::auth::routes::github_callback,
        crate::auth::routes::logout,
        crate::auth::routes::accept_legal_terms,
        crate::auth::routes::me,
        crate::http::workspaces::list,
        crate::http::workspaces::create,
        crate::http::workspaces::get_one,
        crate::http::workspaces::update,
        crate::http::workspaces::delete,
        crate::http::members::list,
        crate::http::members::update_role,
        crate::http::members::remove,
        crate::http::incidents::list,
        crate::http::incidents::create,
        crate::http::incidents::add_update,
        crate::http::notifications::list_notifications,
        crate::http::notifications::list_channels,
        crate::http::notifications::create_channel,
        crate::http::notifications::update_channel,
        crate::http::notifications::delete_channel,
        crate::http::notifications::test_channel,
        crate::http::notifications::list_channel_deliveries,
        crate::http::custom_domains::list,
        crate::http::custom_domains::create,
        crate::http::custom_domains::verify,
        crate::http::custom_domains::remove,
        crate::http::deployments::get_access,
        crate::http::deployments::request_access,
        crate::http::deployments::list_credentials,
        crate::http::deployments::create_credential,
        crate::http::deployments::list_services,
        crate::http::deployments::create_service,
        crate::http::deployments::get_service,
        crate::http::deployments::update_service_settings,
        crate::http::deployments::delete_service,
        crate::http::deployments::set_service_secrets,
        crate::http::deployments::set_service_env,
        crate::http::deployments::list_service_volumes,
        crate::http::deployments::create_service_volume,
        crate::http::deployments::update_service_volume,
        crate::http::deployments::delete_service_volume,
        crate::http::deployments::list_deployments,
        crate::http::deployments::create_deployment,
        crate::http::deployments::rollback_service,
        crate::http::deployments::stop_service,
        crate::http::deployments::list_service_domains,
        crate::http::deployments::create_service_domain,
        crate::http::deployments::verify_service_domain,
        crate::http::deployments::remove_service_domain,
        crate::http::deployments::list_events,
        crate::http::deployments::list_logs,
        crate::http::deployments::list_metrics,
        crate::http::deployments::list_regions,
        crate::http::sandboxes::list_sandboxes,
        crate::http::sandboxes::create_sandbox,
        crate::http::sandboxes::get_sandbox,
        crate::http::sandboxes::update_sandbox,
        crate::http::sandboxes::delete_sandbox,
        crate::http::sandboxes::exec_sandbox,
        crate::http::sandboxes::list_checkpoints,
        crate::http::sandboxes::create_checkpoint,
        crate::http::sandboxes::restore_checkpoint,
        crate::http::sandboxes::delete_checkpoint,
        crate::http::public_sandboxes::list_sandboxes,
        crate::http::public_sandboxes::create_sandbox,
        crate::http::public_sandboxes::get_sandbox,
        crate::http::public_sandboxes::destroy_sandbox,
        crate::http::public_sandboxes::exec_sandbox,
        crate::http::public_sandboxes::list_checkpoints,
        crate::http::public_sandboxes::create_checkpoint,
        crate::http::public_sandboxes::restore_checkpoint,
        crate::http::public_sandboxes::delete_checkpoint,
        crate::http::sandboxes::list_api_tokens,
        crate::http::sandboxes::create_api_token,
        crate::http::sandboxes::revoke_api_token,
        crate::http::object_storage::list_regions,
        crate::http::object_storage::list_buckets,
        crate::http::object_storage::create_bucket,
        crate::http::object_storage::get_bucket,
        crate::http::object_storage::delete_bucket,
        crate::http::billing::summary,
        crate::http::billing::get_customer,
        crate::http::billing::list_plans,
        crate::http::billing::attach,
        crate::http::billing::cancel_subscription,
        crate::http::billing::renew_subscription,
        crate::http::billing::cancel_downgrade,
        crate::http::billing::open_portal,
        crate::http::billing::setup_payment,
        crate::http::pricing::public_pricing,
        crate::http::regions::list,
        crate::http::invites::create,
        crate::http::invites::list,
        crate::http::invites::revoke,
        crate::http::invites::preview,
        crate::http::invites::accept,
        crate::http::monitors::list,
        crate::http::monitors::create,
        crate::http::monitors::get_one,
        crate::http::monitors::update,
        crate::http::monitors::delete,
        crate::http::monitors::dsl_validate,
        crate::http::monitors::dsl_test,
        crate::http::checks::list_checks,
        crate::http::checks::stats,
        crate::http::checks::latency_series,
        crate::http::public_status::get_status,
        crate::http::public_status::get_status_by_domain,
        crate::http::public_status::get_summary,
        crate::http::public_status::get_summary_by_domain,
    ),
    components(schemas(
        crate::http::health::HealthResponse,
        crate::auth::routes::CredsPayload,
        crate::auth::routes::RegisterPayload,
        crate::auth::routes::AuthConfig,
        crate::auth::routes::GithubStartQuery,
        crate::auth::routes::GithubCallbackQuery,
        crate::auth::routes::UserView,
        crate::auth::routes::RegisterResponse,
        crate::auth::routes::MeResponse,
        crate::auth::routes::AuthResponse,
        crate::auth::routes::OkResponse,
        crate::auth::routes::ForgotPasswordPayload,
        crate::auth::routes::ResetPasswordPayload,
        crate::http::workspaces::WorkspaceView,
        crate::http::workspaces::CreateWorkspaceBody,
        crate::http::workspaces::UpdateWorkspaceBody,
        crate::http::members::MemberView,
        crate::http::members::UpdateRole,
        crate::http::incidents::IncidentView,
        crate::http::incidents::IncidentUpdateView,
        crate::http::incidents::CreateIncidentBody,
        crate::http::incidents::IncidentUpdateBody,
        crate::http::notifications::NotificationView,
        crate::http::notifications::NotificationChannelView,
        crate::http::notifications::NotificationDeliveryView,
        crate::http::notifications::CreateNotificationChannel,
        crate::http::notifications::UpdateNotificationChannel,
        crate::http::notifications::TestChannelResponse,
        crate::http::notifications::OkResponse,
        crate::http::custom_domains::CustomDomainView,
        crate::http::custom_domains::CreateCustomDomainBody,
        crate::http::deployments::DeployAccessView,
        crate::http::deployments::DeployRegistryCredentialView,
        crate::http::deployments::DeployServiceView,
        crate::http::deployments::DeployDeploymentView,
        crate::http::deployments::DeployServiceDomainView,
        crate::http::deployments::DeployServiceVolumeView,
        crate::http::deployments::DeployEventView,
        crate::http::deployments::DeployLogLineView,
        crate::http::deployments::DeployMetricPointView,
        crate::http::deployments::CreateRegistryCredentialBody,
        crate::http::deployments::CreateServiceBody,
        crate::http::deployments::UpdateServiceSettingsBody,
        crate::http::deployments::SetServiceSecretsBody,
        crate::http::deployments::SetServiceEnvBody,
        crate::http::deployments::CreateServiceVolumeBody,
        crate::http::deployments::UpdateServiceVolumeBody,
        crate::http::deployments::CreateDeploymentBody,
        crate::http::deployments::CreateServiceDomainBody,
        crate::http::sandbox_service::DeploySandboxView,
        crate::http::sandboxes::CreateSandboxBody,
        crate::http::sandboxes::UpdateSandboxBody,
        crate::http::sandboxes::ExecSandboxBody,
        crate::http::sandboxes::ExecSandboxView,
        crate::http::sandbox_service::SandboxCheckpointView,
        crate::http::sandboxes::CreateCheckpointBody,
        crate::http::sandboxes::CreateSandboxApiTokenBody,
        crate::http::sandbox_service::SandboxApiTokenView,
        crate::http::sandbox_service::CreatedSandboxApiToken,
        crate::http::object_storage::CreateObjectStorageBucketBody,
        crate::http::object_storage_service::ObjectStorageBucketView,
        crate::http::object_storage_service::CreatedObjectStorageBucketView,
        crate::http::public_sandboxes::PublicSandbox,
        crate::http::public_sandboxes::PublicCreateSandboxBody,
        crate::http::public_sandboxes::PublicExecBody,
        crate::http::public_sandboxes::PublicExecResult,
        crate::http::public_sandboxes::PublicCheckpoint,
        crate::http::public_sandboxes::PublicCreateCheckpointBody,
        deploy::DeployRegion,
        tigris::DeployRegion,
        crate::http::billing::BillingSummary,
        crate::http::billing::BillingPlanSummary,
        crate::http::billing::BillingPlanPriceSummary,
        crate::http::billing::BillingPlanItemSummary,
        crate::http::billing::BillingBalanceSummary,
        crate::http::billing::AttachBody,
        crate::http::billing::PortalBody,
        crate::http::billing::SetupPaymentBody,
        crate::http::pricing::PublicPricingResponse,
        crate::http::pricing::PublicPricingPlan,
        crate::http::pricing::PublicPlanPrice,
        crate::http::pricing::PublicPlanFeature,
        crate::http::pricing::PublicUsagePrice,
        crate::http::pricing::PublicPricingFeature,
        crate::regions::RegionView,
        crate::regions::MonitorRegionView,
        crate::http::invites::CreateInviteBody,
        crate::http::invites::InviteCreated,
        crate::http::invites::InviteRow,
        crate::http::invites::InvitePreview,
        crate::http::monitors::CreateMonitor,
        crate::http::monitors::UpdateMonitor,
        crate::http::monitors::MonitorView,
        crate::http::monitors::DslValidateBody,
        crate::http::monitors::DslValidateResponse,
        crate::http::monitors::DslError,
        crate::http::monitors::DslDiagnostic,
        crate::http::monitors::DslTestBody,
        crate::http::monitors::DslTestResponse,
        crate::http::monitors::DslOutcome,
        crate::http::checks::CheckRow,
        crate::http::checks::StatsResponse,
        crate::http::checks::LatencyPoint,
        crate::http::public_status::DayBucket,
        crate::http::public_status::PublicMonitor,
        crate::http::public_status::PublicGroup,
        crate::http::public_status::PublicIncident,
        crate::http::public_status::PublicIncidentUpdate,
        crate::http::public_status::StatusStyle,
        crate::http::public_status::PublicStatus,
        crate::http::public_status::StatuspageSummary,
        crate::http::public_status::StatuspagePage,
        crate::http::public_status::StatuspageStatus,
        crate::http::public_status::StatuspageComponent,
        crate::http::public_status::StatuspageIncident,
        crate::http::public_status::StatuspageScheduledMaintenance,
        crate::http::public_status::StatuspageIncidentUpdate,
        entity::user::Model,
        entity::session::Model,
        entity::workspace::Model,
        entity::workspace_member::Model,
        entity::workspace_member::WorkspaceRole,
        entity::workspace_invite::Model,
        entity::monitor::Model,
        entity::monitor::MonitorKind,
        entity::check::Model,
        entity::region::Model,
        entity::monitor_region::Model,
        entity::monitor_region_state::Model,
        entity::custom_domain::Model,
    )),
    tags(
        (name = "system",     description = "Health and metadata"),
        (name = "auth",       description = "Registration, login, sessions"),
        (name = "workspaces", description = "Workspaces (personal + teams)"),
        (name = "members",    description = "Workspace membership"),
        (name = "incidents",  description = "Private incident history"),
        (name = "notifications", description = "Notification history and channels"),
        (name = "custom domains", description = "Cloudflare-backed custom status domains"),
        (name = "deployments", description = "Private-preview Docker deployments"),
        (name = "sandboxes", description = "Public sandbox API (Railway-style)"),
        (name = "billing", description = "Polar billing proxy"),
        (name = "pricing", description = "Public pricing metadata"),
        (name = "regions", description = "Probe regions"),
        (name = "invites",    description = "Workspace invites"),
        (name = "monitors",   description = "Monitor CRUD"),
        (name = "checks",     description = "Check history and uptime stats"),
        (name = "public",     description = "Public status pages"),
    ),
    modifiers(&SecurityAddon),
)]
pub struct ApiDoc;

struct SecurityAddon;

impl Modify for SecurityAddon {
    fn modify(&self, openapi: &mut utoipa::openapi::OpenApi) {
        let components = openapi
            .components
            .as_mut()
            .expect("components registered by paths/schemas above");
        components.add_security_scheme(
            "bearerAuth",
            SecurityScheme::Http(
                HttpBuilder::new()
                    .scheme(HttpAuthScheme::Bearer)
                    .bearer_format("JWT")
                    .build(),
            ),
        );
        components.add_security_scheme(
            "sandboxApiToken",
            SecurityScheme::Http(
                HttpBuilder::new()
                    .scheme(HttpAuthScheme::Bearer)
                    .bearer_format("prd_sbx_…")
                    .description(Some(
                        "Workspace sandbox API token. Also accepted via X-Produktive-Sandbox-Token header.",
                    ))
                    .build(),
            ),
        );
    }
}

pub fn routes() -> Router<AppState> {
    Router::new().route("/docs.json", get(spec))
}

async fn spec() -> Json<utoipa::openapi::OpenApi> {
    Json(ApiDoc::openapi())
}
