/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["auth_config"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["forgot_password"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/github/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["github_callback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/github/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["github_start"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["reset_password"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/invites/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["preview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/invites/{token}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["accept"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pricing/public": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["public_pricing"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/custom-domains/authorize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["authorize"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/status/by-domain/{domain}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_status_by_domain"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/status/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["workspaces_list"];
        put?: never;
        post: operations["workspaces_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{wid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["workspaces_get"];
        put?: never;
        post?: never;
        delete: operations["workspaces_delete"];
        options?: never;
        head?: never;
        patch: operations["workspaces_update"];
        trace?: never;
    };
    "/api/workspaces/{wid}/billing/attach": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["attach"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{wid}/billing/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["cancel_subscription"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{wid}/billing/cancel-downgrade": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["cancel_downgrade"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{wid}/billing/customer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_customer"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{wid}/billing/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_plans"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{wid}/billing/portal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["open_portal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{wid}/billing/renew": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["renew_subscription"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{wid}/billing/setup-payment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["setup_payment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{wid}/billing/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["summary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{wid}/custom-domains": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["custom_domains_list"];
        put?: never;
        post: operations["custom_domains_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{wid}/custom-domains/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["custom_domains_remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{wid}/custom-domains/{id}/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["verify"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{wid}/incidents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["incidents_list"];
        put?: never;
        post: operations["incidents_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{wid}/incidents/{id}/updates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["add_update"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{wid}/invites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["invites_list"];
        put?: never;
        post: operations["invites_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{wid}/invites/{iid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["revoke"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{wid}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["members_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{wid}/members/{uid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["members_remove"];
        options?: never;
        head?: never;
        patch: operations["update_role"];
        trace?: never;
    };
    "/api/workspaces/{wid}/monitors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["monitors_list"];
        put?: never;
        post: operations["monitors_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{wid}/monitors/dsl/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["dsl_validate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{wid}/monitors/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["monitors_get"];
        put?: never;
        post?: never;
        delete: operations["monitors_delete"];
        options?: never;
        head?: never;
        patch: operations["monitors_update"];
        trace?: never;
    };
    "/api/workspaces/{wid}/monitors/{id}/checks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_checks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{wid}/monitors/{id}/dsl/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["dsl_test"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{wid}/monitors/{id}/latency": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["latency_series"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{wid}/monitors/{id}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["stats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{wid}/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_notifications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{wid}/notifications/channels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_channels"];
        put?: never;
        post: operations["create_channel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{wid}/notifications/channels/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["delete_channel"];
        options?: never;
        head?: never;
        patch: operations["update_channel"];
        trace?: never;
    };
    "/api/workspaces/{wid}/notifications/channels/{id}/deliveries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_channel_deliveries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{wid}/notifications/channels/{id}/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["test_channel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{wid}/regions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["regions_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AttachBody: {
            plan_id: string;
            success_url?: string | null;
        };
        AuthConfig: {
            /** @description Whether GitHub OAuth login is configured on this server. */
            github_enabled: boolean;
        };
        AuthResponse: {
            token: string;
            user: components["schemas"]["UserView"];
        };
        AuthorizeCustomDomainQuery: {
            domain: string;
        };
        BillingBalanceSummary: {
            feature_id: string;
            /** Format: double */
            granted?: number | null;
            /** Format: int64 */
            next_reset_at?: number | null;
            /** Format: double */
            remaining?: number | null;
            unlimited: boolean;
            /** Format: double */
            usage?: number | null;
        };
        BillingPlanItemSummary: {
            feature_id: string;
            /** Format: double */
            included?: number | null;
            primary_text?: string | null;
            secondary_text?: string | null;
            unlimited: boolean;
        };
        BillingPlanPriceSummary: {
            /** Format: double */
            amount?: number | null;
            interval?: string | null;
            primary_text?: string | null;
            secondary_text?: string | null;
        };
        BillingPlanSummary: {
            current: boolean;
            description?: string | null;
            id: string;
            items: components["schemas"]["BillingPlanItemSummary"][];
            name: string;
            price?: null | components["schemas"]["BillingPlanPriceSummary"];
        };
        BillingSummary: {
            balances: {
                [key: string]: components["schemas"]["BillingBalanceSummary"];
            };
            billing_enabled: boolean;
            current_plan_id?: string | null;
            current_plan_name?: string | null;
            customer_id: string;
            plans: components["schemas"]["BillingPlanSummary"][];
            portal_available: boolean;
            scheduled_plan_id?: string | null;
            scheduled_plan_name?: string | null;
            stripe_customer_id?: string | null;
            /** Format: int64 */
            subscription_canceled_at?: number | null;
            /** Format: int64 */
            subscription_current_period_end?: number | null;
            subscription_status?: string | null;
        };
        /**
         * @description Delivery target type for a notification channel. Stored as a SMALLINT
         *     (`webhook = 0`, `slack = 1`, `discord = 2`); the wire format is the
         *     lowercase name so the API stays self-describing.
         * @enum {string}
         */
        ChannelKind: "webhook" | "slack" | "discord";
        CheckRow: {
            error_message?: string | null;
            /** Format: int32 */
            latency_ms?: number | null;
            /** Format: uuid */
            region_id?: string | null;
            region_name?: string | null;
            region_slug?: string | null;
            /** Format: int32 */
            status: number;
            /** Format: int32 */
            status_code?: number | null;
            /** Format: date-time */
            time: string;
        };
        CreateCustomDomainBody: {
            hostname: string;
        };
        CreateIncidentBody: {
            message: string;
            /** Format: uuid */
            monitor_id?: string | null;
            severity?: string | null;
            title: string;
        };
        CreateInviteBody: {
            email: string;
            role?: components["schemas"]["WorkspaceRole"];
        };
        CreateMonitor: {
            dsl_source?: string | null;
            enabled?: boolean;
            expected_body_contains?: string | null;
            /** Format: int32 */
            expected_status?: number | null;
            /** Format: int32 */
            interval_seconds?: number | null;
            kind?: null | components["schemas"]["MonitorKind"];
            name: string;
            region_slugs?: string[] | null;
            target?: string | null;
            /** Format: int32 */
            timeout_ms?: number | null;
        };
        CreateNotificationChannel: {
            enabled?: boolean;
            kind?: components["schemas"]["ChannelKind"];
            name: string;
            notify_resolved?: boolean;
            webhook_url: string;
        };
        CreateWorkspaceBody: {
            name: string;
        };
        CredsPayload: {
            email: string;
            password: string;
        };
        CustomDomainView: {
            cname_target: string;
            /** Format: date-time */
            created_at: string;
            hostname: string;
            /** Format: uuid */
            id: string;
            proxy_ipv4?: string | null;
            proxy_ipv6?: string | null;
            /** Format: date-time */
            updated_at: string;
            verification_name: string;
            verification_value: string;
            /** Format: date-time */
            verified_at?: string | null;
            /** Format: uuid */
            workspace_id: string;
        };
        /**
         * @description One day of aggregated check results for the uptime bar. The frontend colors
         *     each day and computes uptime % from these counts.
         */
        DayBucket: {
            /**
             * Format: int32
             * @description Mean response time (ms) over checks that recorded a latency that day.
             *     `None` when no successful checks were recorded.
             */
            avg_latency_ms?: number | null;
            /** @description UTC calendar day, `YYYY-MM-DD`. */
            date: string;
            /** Format: int64 */
            degraded: number;
            /** Format: int64 */
            down: number;
            /** Format: int64 */
            total: number;
            /** Format: int64 */
            up: number;
        };
        DslDiagnostic: {
            /** Format: int32 */
            col: number;
            /** Format: int32 */
            line: number;
            message: string;
            severity: string;
        };
        DslError: {
            /** Format: int32 */
            col: number;
            /** Format: int32 */
            line: number;
            message: string;
        };
        DslOutcome: {
            kind: string;
            message?: string | null;
            rule_index?: number | null;
        };
        DslTestBody: {
            sample?: unknown;
            source: string;
        };
        DslTestResponse: {
            error?: null | components["schemas"]["DslError"];
            ok: boolean;
            outcome?: null | components["schemas"]["DslOutcome"];
        };
        DslValidateBody: {
            source: string;
        };
        DslValidateResponse: {
            ast?: unknown;
            diagnostics?: components["schemas"]["DslDiagnostic"][];
            error?: null | components["schemas"]["DslError"];
            ok: boolean;
        };
        ForgotPasswordPayload: {
            email: string;
        };
        GithubCallbackQuery: {
            code?: string | null;
            error?: string | null;
            state?: string | null;
        };
        GithubStartQuery: {
            redirect?: string | null;
        };
        HealthResponse: {
            ok: boolean;
        };
        IncidentUpdateBody: {
            message: string;
            /** @description `investigating`, `identified`, `monitoring`, or `resolved`. */
            status?: string | null;
        };
        IncidentUpdateView: {
            /** Format: date-time */
            created_at: string;
            /** Format: uuid */
            created_by?: string | null;
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            incident_id: string;
            message: string;
            status: string;
        };
        IncidentView: {
            error_message?: string | null;
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            last_seen_at: string;
            /** Format: uuid */
            monitor_id?: string | null;
            monitor_kind?: string | null;
            monitor_name?: string | null;
            monitor_slug?: string | null;
            /** Format: date-time */
            resolved_at?: string | null;
            severity: string;
            source: string;
            /** Format: date-time */
            started_at: string;
            status: string;
            title: string;
            updates: components["schemas"]["IncidentUpdateView"][];
            /** Format: uuid */
            workspace_id: string;
        };
        InviteCreated: {
            accept_url: string;
            email: string;
            email_sent: boolean;
            /** Format: date-time */
            expires_at: string;
            /** Format: uuid */
            id: string;
            role: components["schemas"]["WorkspaceRole"];
            token: string;
        };
        InvitePreview: {
            email: string;
            /** Format: date-time */
            expires_at: string;
            role: components["schemas"]["WorkspaceRole"];
            /** Format: uuid */
            workspace_id: string;
            workspace_name: string;
        };
        InviteRow: {
            /** Format: date-time */
            accepted_at?: string | null;
            /** Format: date-time */
            created_at: string;
            email: string;
            /** Format: date-time */
            expires_at: string;
            /** Format: uuid */
            id: string;
            role: components["schemas"]["WorkspaceRole"];
        };
        /**
         * @description One time-bucket of the response-time chart. `avg_latency_ms` is the mean over
         *     checks in the bucket that recorded a latency; `down > 0` marks an outage band.
         */
        LatencyPoint: {
            /** Format: int32 */
            avg_latency_ms?: number | null;
            /** Format: int64 */
            down: number;
            /** Format: date-time */
            time: string;
            /** Format: int64 */
            total: number;
            /** Format: int64 */
            up: number;
        };
        MeResponse: {
            /** Format: date-time */
            created_at: string;
            email: string;
            /** Format: uuid */
            id: string;
            is_admin: boolean;
            /** Format: uuid */
            personal_workspace_id?: string | null;
        };
        MemberView: {
            /** Format: date-time */
            created_at: string;
            email: string;
            role: components["schemas"]["WorkspaceRole"];
            /** Format: uuid */
            user_id: string;
        };
        Model: {
            /** Format: date-time */
            created_at: string;
            /** Format: uuid */
            id: string;
            role: components["schemas"]["WorkspaceRole"];
            /** Format: uuid */
            user_id: string;
            /** Format: uuid */
            workspace_id: string;
        };
        /** @enum {string} */
        MonitorKind: "http" | "tcp" | "ping" | "postgres" | "redis" | "ssh";
        MonitorRegionView: {
            enabled: boolean;
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            last_checked_at?: string | null;
            last_error?: string | null;
            /** Format: int32 */
            last_latency_ms?: number | null;
            /** Format: int32 */
            last_status?: number | null;
            name: string;
            slug: string;
        };
        MonitorView: {
            /** Format: date-time */
            billing_paused_at?: string | null;
            /** Format: int32 */
            canvas_x: number;
            /** Format: int32 */
            canvas_y: number;
            /** Format: date-time */
            created_at: string;
            dsl_source?: string | null;
            enabled: boolean;
            expected_body_contains?: string | null;
            /** Format: int32 */
            expected_status?: number | null;
            /** Format: uuid */
            id: string;
            /** Format: int32 */
            interval_seconds: number;
            kind: components["schemas"]["MonitorKind"];
            /** Format: date-time */
            last_checked_at?: string | null;
            /** Format: int32 */
            last_latency_ms?: number | null;
            /** Format: int32 */
            last_status?: number | null;
            name: string;
            regions: components["schemas"]["MonitorRegionView"][];
            slug: string;
            target: string;
            /** Format: int32 */
            timeout_ms: number;
            /** Format: date-time */
            updated_at: string;
            /** Format: uuid */
            workspace_id: string;
        };
        NotificationChannelView: {
            /** Format: date-time */
            created_at: string;
            enabled: boolean;
            /** Format: uuid */
            id: string;
            kind: string;
            /** Format: date-time */
            last_delivery_at?: string | null;
            last_delivery_error?: string | null;
            last_delivery_status?: string | null;
            masked_url: string;
            name: string;
            notify_resolved: boolean;
            /** Format: date-time */
            updated_at: string;
            /** Format: uuid */
            workspace_id: string;
        };
        NotificationDeliveryView: {
            /** Format: uuid */
            channel_id: string;
            /** Format: date-time */
            created_at: string;
            error_message?: string | null;
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            notification_id: string;
            notification_title?: string | null;
            /** Format: date-time */
            sent_at?: string | null;
            status: string;
        };
        NotificationView: {
            body: string;
            /** Format: date-time */
            created_at: string;
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            incident_id?: string | null;
            kind: string;
            /** Format: uuid */
            monitor_id?: string | null;
            monitor_name?: string | null;
            title: string;
            /** Format: uuid */
            workspace_id: string;
        };
        OkResponse: {
            ok: boolean;
        };
        PortalBody: {
            return_url?: string | null;
        };
        PublicGroup: {
            id: string;
            monitors: components["schemas"]["PublicMonitor"][];
            name?: string | null;
        };
        PublicIncident: {
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            last_seen_at: string;
            /** Format: uuid */
            monitor_id?: string | null;
            monitor_name?: string | null;
            monitor_slug?: string | null;
            /** Format: date-time */
            resolved_at?: string | null;
            severity: string;
            source: string;
            /** Format: date-time */
            started_at: string;
            status: string;
            title: string;
            updates: components["schemas"]["PublicIncidentUpdate"][];
        };
        PublicIncidentUpdate: {
            /** Format: date-time */
            created_at: string;
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            incident_id: string;
            message: string;
            status: string;
        };
        PublicMonitor: {
            /** @description Oldest-to-newest daily history, exactly `HISTORY_DAYS` entries (gaps zero-filled). */
            history: components["schemas"]["DayBucket"][];
            /** Format: uuid */
            id: string;
            kind: string;
            /** Format: date-time */
            last_checked_at?: string | null;
            /** Format: int32 */
            last_latency_ms?: number | null;
            name: string;
            status: string;
        };
        PublicPlanFeature: {
            feature_id: string;
            feature_type?: string | null;
            /** Format: double */
            included?: number | null;
            name?: string | null;
            primary_text?: string | null;
            reset_interval?: string | null;
            secondary_text?: string | null;
            unlimited: boolean;
            usage_price?: null | components["schemas"]["PublicUsagePrice"];
        };
        PublicPlanPrice: {
            /** Format: double */
            amount?: number | null;
            interval?: string | null;
            primary_text?: string | null;
            secondary_text?: string | null;
        };
        PublicPricingFeature: {
            consumable: boolean;
            display_plural?: string | null;
            display_singular?: string | null;
            feature_type?: string | null;
            id: string;
            name?: string | null;
        };
        PublicPricingPlan: {
            description?: string | null;
            features: components["schemas"]["PublicPlanFeature"][];
            id: string;
            name: string;
            price?: null | components["schemas"]["PublicPlanPrice"];
        };
        PublicPricingResponse: {
            billing_enabled: boolean;
            features: components["schemas"]["PublicPricingFeature"][];
            /** Format: date-time */
            generated_at: string;
            plans: components["schemas"]["PublicPricingPlan"][];
        };
        PublicStatus: {
            description?: string | null;
            /** Format: date-time */
            generated_at: string;
            groups: components["schemas"]["PublicGroup"][];
            incidents: components["schemas"]["PublicIncident"][];
            monitors: components["schemas"]["PublicMonitor"][];
            overall: string;
            style: components["schemas"]["StatusStyle"];
            title?: string | null;
            workspace_name: string;
        };
        PublicUsagePrice: {
            /** Format: double */
            amount?: number | null;
            billing_method?: string | null;
            /** Format: double */
            billing_units?: number | null;
            interval?: string | null;
            /** Format: double */
            max_purchase?: number | null;
            /** Format: double */
            unit_amount?: number | null;
        };
        RegionView: {
            capabilities: string[];
            enabled: boolean;
            /** Format: date-time */
            heartbeat_at?: string | null;
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
            version?: string | null;
        };
        RegisterResponse: {
            /** Format: uuid */
            personal_workspace_id: string;
            user: components["schemas"]["UserView"];
        };
        ResetPasswordPayload: {
            password: string;
            token: string;
        };
        SetupPaymentBody: {
            plan_id?: string | null;
            success_url?: string | null;
        };
        StatsResponse: {
            /** Format: double */
            avg_latency_ms?: number | null;
            /** Format: int64 */
            down: number;
            /** Format: int64 */
            total: number;
            /** Format: int64 */
            up: number;
            /** Format: double */
            uptime_percent: number;
            /** Format: int64 */
            window_seconds: number;
        };
        StatusStyle: {
            accent?: string | null;
            header_link?: string | null;
            logo_url?: string | null;
            theme: string;
        };
        TestChannelResponse: {
            ok: boolean;
        };
        UpdateMonitor: {
            /** Format: int32 */
            canvas_x?: number | null;
            /** Format: int32 */
            canvas_y?: number | null;
            dsl_source?: string | null;
            enabled?: boolean | null;
            expected_body_contains?: string | null;
            /** Format: int32 */
            expected_status?: number | null;
            /** Format: int32 */
            interval_seconds?: number | null;
            kind?: null | components["schemas"]["MonitorKind"];
            name?: string | null;
            region_slugs?: string[] | null;
            target?: string | null;
            /** Format: int32 */
            timeout_ms?: number | null;
        };
        UpdateNotificationChannel: {
            enabled?: boolean | null;
            name?: string | null;
            notify_resolved?: boolean | null;
        };
        UpdateRole: {
            role: components["schemas"]["WorkspaceRole"];
        };
        UpdateWorkspaceBody: {
            name?: string | null;
            slug?: string | null;
            status_page_config?: Record<string, never> | null;
            status_page_description?: string | null;
            status_page_enabled?: boolean | null;
            status_page_title?: string | null;
            status_slug?: string | null;
        };
        UserView: {
            /** Format: date-time */
            created_at: string;
            email: string;
            /** Format: uuid */
            id: string;
            is_admin: boolean;
        };
        Value: unknown;
        /** @enum {string} */
        WorkspaceRole: "owner" | "member";
        WorkspaceView: {
            checkout_url?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: uuid */
            id: string;
            is_personal: boolean;
            name: string;
            /** Format: uuid */
            owner_id: string;
            requires_upgrade?: boolean | null;
            role: components["schemas"]["WorkspaceRole"];
            slug: string;
            status_page_config?: Record<string, never> | null;
            status_page_description?: string | null;
            status_page_enabled: boolean;
            status_page_title?: string | null;
            status_slug?: string | null;
            /** Format: date-time */
            updated_at: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    auth_config: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthConfig"];
                };
            };
        };
    };
    forgot_password: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgotPasswordPayload"];
            };
        };
        responses: {
            /** @description Always ok; reveals nothing about whether the email exists */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    github_callback: {
        parameters: {
            query?: {
                code?: string;
                state?: string;
                error?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirects to the app with an auth token */
            303: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid OAuth callback */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description GitHub login is not configured */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    github_start: {
        parameters: {
            query?: {
                redirect?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirects to GitHub OAuth */
            303: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description GitHub login is not configured */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CredsPayload"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Missing or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            /** @description Missing or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CredsPayload"];
            };
        };
        responses: {
            /** @description User created and personal workspace assigned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisterResponse"];
                };
            };
            /** @description Invalid email or password */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Email already registered */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    reset_password: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordPayload"];
            };
        };
        responses: {
            /** @description Password updated; auto-logged-in */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Invalid/expired/used token or password too short */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    preview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description invite token (hex) */
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvitePreview"];
                };
            };
            /** @description Expired / already accepted */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Token email does not match auth user */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unknown token */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    accept: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description invite token (hex) */
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Expired / already accepted */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Token email does not match auth user */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unknown token */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    public_pricing: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicPricingResponse"];
                };
            };
        };
    };
    authorize: {
        parameters: {
            query: {
                /** @description custom domain requested by Caddy */
                domain: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Domain is authorized for on-demand TLS */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Domain is not authorized */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_status_by_domain: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description custom status page domain */
                domain: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicStatus"];
                };
            };
            /** @description Status page not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_status: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description status page slug */
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicStatus"];
                };
            };
            /** @description Status page not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    workspaces_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceView"][];
                };
            };
        };
    };
    workspaces_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWorkspaceBody"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceView"];
                };
            };
            /** @description name required */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    workspaces_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description workspace id */
                wid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceView"];
                };
            };
            /** @description Not a member */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    workspaces_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description workspace id */
                wid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Personal workspace cannot be deleted */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Owner only */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    workspaces_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description workspace id */
                wid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateWorkspaceBody"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Model"];
                };
            };
            /** @description Owner only */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    attach: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                wid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AttachBody"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    cancel_subscription: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                wid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    cancel_downgrade: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                wid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    get_customer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                wid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    list_plans: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                wid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    open_portal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                wid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PortalBody"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    renew_subscription: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                wid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    setup_payment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                wid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetupPaymentBody"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    summary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                wid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BillingSummary"];
                };
            };
        };
    };
    custom_domains_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description workspace id */
                wid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomDomainView"][];
                };
            };
        };
    };
    custom_domains_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description workspace id */
                wid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCustomDomainBody"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomDomainView"];
                };
            };
            /** @description Invalid hostname */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Owner only */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Domain already added */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    custom_domains_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description workspace id */
                wid: string;
                /** @description custom domain id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
        };
    };
    verify: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description workspace id */
                wid: string;
                /** @description custom domain id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomDomainView"];
                };
            };
            /** @description TXT verification record was not found */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Owner only */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    incidents_list: {
        parameters: {
            query?: {
                /** @description `open`, `resolved`, or `all`. */
                status?: string;
                limit?: number;
            };
            header?: never;
            path: {
                /** @description workspace id or slug */
                wid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidentView"][];
                };
            };
        };
    };
    incidents_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description workspace id or slug */
                wid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateIncidentBody"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidentView"];
                };
            };
        };
    };
    add_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description workspace id or slug */
                wid: string;
                /** @description incident id */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IncidentUpdateBody"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidentView"];
                };
            };
        };
    };
    invites_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description workspace id */
                wid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InviteRow"][];
                };
            };
            /** @description Owner only */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    invites_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description workspace id */
                wid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateInviteBody"];
            };
        };
        responses: {
            /** @description Token returned exactly once */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InviteCreated"];
                };
            };
            /** @description Invalid email */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Owner only */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invite already pending for this email */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    revoke: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description workspace id */
                wid: string;
                /** @description invite id */
                iid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Owner only */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invite not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    members_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description workspace id */
                wid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberView"][];
                };
            };
        };
    };
    members_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description workspace id */
                wid: string;
                /** @description user id to remove (self-leave allowed) */
                uid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Personal workspace / last owner protection */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Owner only (unless self-leave) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Member not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_role: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description workspace id */
                wid: string;
                /** @description user id */
                uid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRole"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Model"];
                };
            };
            /** @description Cannot demote last owner */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Owner only */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Member not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    monitors_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description workspace id */
                wid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonitorView"][];
                };
            };
        };
    };
    monitors_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description workspace id */
                wid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMonitor"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonitorView"];
                };
            };
            /** @description Invalid name/target/dsl */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    dsl_validate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description workspace id */
                wid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DslValidateBody"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DslValidateResponse"];
                };
            };
        };
    };
    monitors_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description workspace id */
                wid: string;
                /** @description monitor id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonitorView"];
                };
            };
            /** @description Monitor not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    monitors_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description workspace id */
                wid: string;
                /** @description monitor id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Monitor not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    monitors_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description workspace id */
                wid: string;
                /** @description monitor id */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMonitor"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonitorView"];
                };
            };
            /** @description Monitor not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_checks: {
        parameters: {
            query?: {
                from?: string;
                to?: string;
                limit?: number;
                region?: string;
            };
            header?: never;
            path: {
                /** @description workspace id or slug */
                wid: string;
                /** @description monitor id or slug */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckRow"][];
                };
            };
            /** @description Monitor not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    dsl_test: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description workspace id */
                wid: string;
                /** @description monitor id */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DslTestBody"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DslTestResponse"];
                };
            };
        };
    };
    latency_series: {
        parameters: {
            query?: {
                window?: string;
                region?: string;
            };
            header?: never;
            path: {
                /** @description workspace id or slug */
                wid: string;
                /** @description monitor id or slug */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LatencyPoint"][];
                };
            };
            /** @description Invalid window */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Monitor not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    stats: {
        parameters: {
            query?: {
                window?: string;
                region?: string;
            };
            header?: never;
            path: {
                /** @description workspace id or slug */
                wid: string;
                /** @description monitor id or slug */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsResponse"];
                };
            };
            /** @description Invalid window */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Monitor not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_notifications: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                /** @description workspace id or slug */
                wid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationView"][];
                };
            };
        };
    };
    list_channels: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description workspace id or slug */
                wid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationChannelView"][];
                };
            };
        };
    };
    create_channel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description workspace id or slug */
                wid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateNotificationChannel"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationChannelView"];
                };
            };
            /** @description Invalid channel */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Owner only */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_channel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description workspace id or slug */
                wid: string;
                /** @description channel id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Owner only */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_channel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description workspace id or slug */
                wid: string;
                /** @description channel id */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateNotificationChannel"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationChannelView"];
                };
            };
            /** @description Owner only */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Channel not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_channel_deliveries: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                /** @description workspace id or slug */
                wid: string;
                /** @description channel id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationDeliveryView"][];
                };
            };
            /** @description Channel not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    test_channel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description workspace id or slug */
                wid: string;
                /** @description channel id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestChannelResponse"];
                };
            };
            /** @description Delivery failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Owner only */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Channel not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    regions_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description workspace id or slug */
                wid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegionView"][];
                };
            };
        };
    };
}
