/* eslint-disable */
import * as types from "./graphql";
import { TypedDocumentNode as DocumentNode } from "@graphql-typed-document-node/core";

/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 * Learn more about it here: https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#reducing-bundle-size
 */
type Documents = {
  "query Issues($status: String, $projectId: String, $labelIds: [String!]) {\n  issues(status: $status, projectId: $projectId, labelIds: $labelIds)\n}\n\nquery Issue($id: String!) {\n  issue(id: $id)\n}\n\nquery Projects($includeArchived: Boolean) {\n  projects(includeArchived: $includeArchived)\n}\n\nquery Project($id: String!) {\n  project(id: $id)\n}\n\nquery Labels($includeArchived: Boolean) {\n  labels(includeArchived: $includeArchived)\n}\n\nquery Label($id: String!) {\n  label(id: $id)\n}\n\nquery IssueStatuses {\n  issueStatuses\n}\n\nquery Members {\n  members\n}\n\nquery Inbox {\n  inbox\n}\n\nquery Preferences {\n  preferences\n}\n\nquery Tabs {\n  tabs\n}\n\nquery Chats {\n  chats\n}\n\nmutation UpdatePreferences($input: PreferencesInput!) {\n  updatePreferences(input: $input)\n}\n\nmutation CreateIssue($input: CreateIssueInput!) {\n  createIssue(input: $input)\n}\n\nmutation UpdateIssue($id: String!, $input: UpdateIssueInput!) {\n  updateIssue(id: $id, input: $input)\n}\n\nmutation DeleteIssue($id: String!) {\n  deleteIssue(id: $id)\n}\n\nmutation CreateIssueStatus($input: IssueStatusInput!) {\n  createIssueStatus(input: $input)\n}\n\nmutation UpdateIssueStatus($id: String!, $input: IssueStatusInput!) {\n  updateIssueStatus(id: $id, input: $input)\n}\n\nmutation DeleteIssueStatus($id: String!, $input: DeleteIssueStatusInput) {\n  deleteIssueStatus(id: $id, input: $input)\n}\n\nmutation ReorderIssueStatuses($statuses: [ReorderIssueStatusInput!]!) {\n  reorderIssueStatuses(statuses: $statuses)\n}\n\nmutation CreateProject($input: CreateProjectInput!) {\n  createProject(input: $input)\n}\n\nmutation UpdateProject($id: String!, $input: UpdateProjectInput!) {\n  updateProject(id: $id, input: $input)\n}\n\nmutation DeleteProject($id: String!) {\n  deleteProject(id: $id)\n}\n\nmutation CreateLabel($input: CreateLabelInput!) {\n  createLabel(input: $input)\n}\n\nmutation UpdateLabel($id: String!, $input: UpdateLabelInput!) {\n  updateLabel(id: $id, input: $input)\n}\n\nmutation DeleteLabel($id: String!) {\n  deleteLabel(id: $id)\n}\n\nmutation OpenTab($input: OpenTabInput!) {\n  openTab(input: $input)\n}\n\nmutation CloseTab($id: String!) {\n  closeTab(id: $id)\n}\n\nmutation CloseAllTabs {\n  closeAllTabs\n}\n\nmutation MarkNotificationRead($id: String!) {\n  markNotificationRead(id: $id)\n}\n\nmutation MarkAllNotificationsRead {\n  markAllNotificationsRead\n}": typeof types.IssuesDocument;
};
const documents: Documents = {
  "query Issues($status: String, $projectId: String, $labelIds: [String!]) {\n  issues(status: $status, projectId: $projectId, labelIds: $labelIds)\n}\n\nquery Issue($id: String!) {\n  issue(id: $id)\n}\n\nquery Projects($includeArchived: Boolean) {\n  projects(includeArchived: $includeArchived)\n}\n\nquery Project($id: String!) {\n  project(id: $id)\n}\n\nquery Labels($includeArchived: Boolean) {\n  labels(includeArchived: $includeArchived)\n}\n\nquery Label($id: String!) {\n  label(id: $id)\n}\n\nquery IssueStatuses {\n  issueStatuses\n}\n\nquery Members {\n  members\n}\n\nquery Inbox {\n  inbox\n}\n\nquery Preferences {\n  preferences\n}\n\nquery Tabs {\n  tabs\n}\n\nquery Chats {\n  chats\n}\n\nmutation UpdatePreferences($input: PreferencesInput!) {\n  updatePreferences(input: $input)\n}\n\nmutation CreateIssue($input: CreateIssueInput!) {\n  createIssue(input: $input)\n}\n\nmutation UpdateIssue($id: String!, $input: UpdateIssueInput!) {\n  updateIssue(id: $id, input: $input)\n}\n\nmutation DeleteIssue($id: String!) {\n  deleteIssue(id: $id)\n}\n\nmutation CreateIssueStatus($input: IssueStatusInput!) {\n  createIssueStatus(input: $input)\n}\n\nmutation UpdateIssueStatus($id: String!, $input: IssueStatusInput!) {\n  updateIssueStatus(id: $id, input: $input)\n}\n\nmutation DeleteIssueStatus($id: String!, $input: DeleteIssueStatusInput) {\n  deleteIssueStatus(id: $id, input: $input)\n}\n\nmutation ReorderIssueStatuses($statuses: [ReorderIssueStatusInput!]!) {\n  reorderIssueStatuses(statuses: $statuses)\n}\n\nmutation CreateProject($input: CreateProjectInput!) {\n  createProject(input: $input)\n}\n\nmutation UpdateProject($id: String!, $input: UpdateProjectInput!) {\n  updateProject(id: $id, input: $input)\n}\n\nmutation DeleteProject($id: String!) {\n  deleteProject(id: $id)\n}\n\nmutation CreateLabel($input: CreateLabelInput!) {\n  createLabel(input: $input)\n}\n\nmutation UpdateLabel($id: String!, $input: UpdateLabelInput!) {\n  updateLabel(id: $id, input: $input)\n}\n\nmutation DeleteLabel($id: String!) {\n  deleteLabel(id: $id)\n}\n\nmutation OpenTab($input: OpenTabInput!) {\n  openTab(input: $input)\n}\n\nmutation CloseTab($id: String!) {\n  closeTab(id: $id)\n}\n\nmutation CloseAllTabs {\n  closeAllTabs\n}\n\nmutation MarkNotificationRead($id: String!) {\n  markNotificationRead(id: $id)\n}\n\nmutation MarkAllNotificationsRead {\n  markAllNotificationsRead\n}":
    types.IssuesDocument,
};

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 *
 *
 * @example
 * ```ts
 * const query = graphql(`query GetUser($id: ID!) { user(id: $id) { name } }`);
 * ```
 *
 * The query argument is unknown!
 * Please regenerate the types.
 */
export function graphql(source: string): unknown;

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: "query Issues($status: String, $projectId: String, $labelIds: [String!]) {\n  issues(status: $status, projectId: $projectId, labelIds: $labelIds)\n}\n\nquery Issue($id: String!) {\n  issue(id: $id)\n}\n\nquery Projects($includeArchived: Boolean) {\n  projects(includeArchived: $includeArchived)\n}\n\nquery Project($id: String!) {\n  project(id: $id)\n}\n\nquery Labels($includeArchived: Boolean) {\n  labels(includeArchived: $includeArchived)\n}\n\nquery Label($id: String!) {\n  label(id: $id)\n}\n\nquery IssueStatuses {\n  issueStatuses\n}\n\nquery Members {\n  members\n}\n\nquery Inbox {\n  inbox\n}\n\nquery Preferences {\n  preferences\n}\n\nquery Tabs {\n  tabs\n}\n\nquery Chats {\n  chats\n}\n\nmutation UpdatePreferences($input: PreferencesInput!) {\n  updatePreferences(input: $input)\n}\n\nmutation CreateIssue($input: CreateIssueInput!) {\n  createIssue(input: $input)\n}\n\nmutation UpdateIssue($id: String!, $input: UpdateIssueInput!) {\n  updateIssue(id: $id, input: $input)\n}\n\nmutation DeleteIssue($id: String!) {\n  deleteIssue(id: $id)\n}\n\nmutation CreateIssueStatus($input: IssueStatusInput!) {\n  createIssueStatus(input: $input)\n}\n\nmutation UpdateIssueStatus($id: String!, $input: IssueStatusInput!) {\n  updateIssueStatus(id: $id, input: $input)\n}\n\nmutation DeleteIssueStatus($id: String!, $input: DeleteIssueStatusInput) {\n  deleteIssueStatus(id: $id, input: $input)\n}\n\nmutation ReorderIssueStatuses($statuses: [ReorderIssueStatusInput!]!) {\n  reorderIssueStatuses(statuses: $statuses)\n}\n\nmutation CreateProject($input: CreateProjectInput!) {\n  createProject(input: $input)\n}\n\nmutation UpdateProject($id: String!, $input: UpdateProjectInput!) {\n  updateProject(id: $id, input: $input)\n}\n\nmutation DeleteProject($id: String!) {\n  deleteProject(id: $id)\n}\n\nmutation CreateLabel($input: CreateLabelInput!) {\n  createLabel(input: $input)\n}\n\nmutation UpdateLabel($id: String!, $input: UpdateLabelInput!) {\n  updateLabel(id: $id, input: $input)\n}\n\nmutation DeleteLabel($id: String!) {\n  deleteLabel(id: $id)\n}\n\nmutation OpenTab($input: OpenTabInput!) {\n  openTab(input: $input)\n}\n\nmutation CloseTab($id: String!) {\n  closeTab(id: $id)\n}\n\nmutation CloseAllTabs {\n  closeAllTabs\n}\n\nmutation MarkNotificationRead($id: String!) {\n  markNotificationRead(id: $id)\n}\n\nmutation MarkAllNotificationsRead {\n  markAllNotificationsRead\n}",
): (typeof documents)["query Issues($status: String, $projectId: String, $labelIds: [String!]) {\n  issues(status: $status, projectId: $projectId, labelIds: $labelIds)\n}\n\nquery Issue($id: String!) {\n  issue(id: $id)\n}\n\nquery Projects($includeArchived: Boolean) {\n  projects(includeArchived: $includeArchived)\n}\n\nquery Project($id: String!) {\n  project(id: $id)\n}\n\nquery Labels($includeArchived: Boolean) {\n  labels(includeArchived: $includeArchived)\n}\n\nquery Label($id: String!) {\n  label(id: $id)\n}\n\nquery IssueStatuses {\n  issueStatuses\n}\n\nquery Members {\n  members\n}\n\nquery Inbox {\n  inbox\n}\n\nquery Preferences {\n  preferences\n}\n\nquery Tabs {\n  tabs\n}\n\nquery Chats {\n  chats\n}\n\nmutation UpdatePreferences($input: PreferencesInput!) {\n  updatePreferences(input: $input)\n}\n\nmutation CreateIssue($input: CreateIssueInput!) {\n  createIssue(input: $input)\n}\n\nmutation UpdateIssue($id: String!, $input: UpdateIssueInput!) {\n  updateIssue(id: $id, input: $input)\n}\n\nmutation DeleteIssue($id: String!) {\n  deleteIssue(id: $id)\n}\n\nmutation CreateIssueStatus($input: IssueStatusInput!) {\n  createIssueStatus(input: $input)\n}\n\nmutation UpdateIssueStatus($id: String!, $input: IssueStatusInput!) {\n  updateIssueStatus(id: $id, input: $input)\n}\n\nmutation DeleteIssueStatus($id: String!, $input: DeleteIssueStatusInput) {\n  deleteIssueStatus(id: $id, input: $input)\n}\n\nmutation ReorderIssueStatuses($statuses: [ReorderIssueStatusInput!]!) {\n  reorderIssueStatuses(statuses: $statuses)\n}\n\nmutation CreateProject($input: CreateProjectInput!) {\n  createProject(input: $input)\n}\n\nmutation UpdateProject($id: String!, $input: UpdateProjectInput!) {\n  updateProject(id: $id, input: $input)\n}\n\nmutation DeleteProject($id: String!) {\n  deleteProject(id: $id)\n}\n\nmutation CreateLabel($input: CreateLabelInput!) {\n  createLabel(input: $input)\n}\n\nmutation UpdateLabel($id: String!, $input: UpdateLabelInput!) {\n  updateLabel(id: $id, input: $input)\n}\n\nmutation DeleteLabel($id: String!) {\n  deleteLabel(id: $id)\n}\n\nmutation OpenTab($input: OpenTabInput!) {\n  openTab(input: $input)\n}\n\nmutation CloseTab($id: String!) {\n  closeTab(id: $id)\n}\n\nmutation CloseAllTabs {\n  closeAllTabs\n}\n\nmutation MarkNotificationRead($id: String!) {\n  markNotificationRead(id: $id)\n}\n\nmutation MarkAllNotificationsRead {\n  markAllNotificationsRead\n}"];

export function graphql(source: string) {
  return (documents as any)[source] ?? {};
}

export type DocumentType<TDocumentNode extends DocumentNode<any, any>> =
  TDocumentNode extends DocumentNode<infer TType, any> ? TType : never;
