/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SRouteImport } from './routes/s'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IncidentsRouteImport } from './routes/incidents'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SSlugRouteImport } from './routes/s_.$slug'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as AuthedWidRouteImport } from './routes/_authed.$wid'
import { Route as SSlugIndexRouteImport } from './routes/s_.$slug.index'
import { Route as AuthedWidIndexRouteImport } from './routes/_authed.$wid.index'
import { Route as SSlugIncidentsRouteImport } from './routes/s_.$slug.incidents'
import { Route as AuthedWidStatusRouteImport } from './routes/_authed.$wid.status'
import { Route as AuthedWidSettingsRouteImport } from './routes/_authed.$wid.settings'
import { Route as AuthedWidMembersRouteImport } from './routes/_authed.$wid.members'
import { Route as AuthedWidIncidentsRouteImport } from './routes/_authed.$wid.incidents'
import { Route as AuthedWidSettingsIndexRouteImport } from './routes/_authed.$wid.settings.index'
import { Route as AuthedWidMonitorsIndexRouteImport } from './routes/_authed.$wid.monitors.index'
import { Route as AuthedWidLogsIndexRouteImport } from './routes/_authed.$wid.logs.index'
import { Route as AuthedWidSettingsWorkersRouteImport } from './routes/_authed.$wid.settings.workers'
import { Route as AuthedWidSettingsNotificationsRouteImport } from './routes/_authed.$wid.settings.notifications'
import { Route as AuthedWidSettingsMembersRouteImport } from './routes/_authed.$wid.settings.members'
import { Route as AuthedWidSettingsLogStorageRouteImport } from './routes/_authed.$wid.settings.log-storage'
import { Route as AuthedWidSettingsBillingRouteImport } from './routes/_authed.$wid.settings.billing'
import { Route as AuthedWidMonitorsNewRouteImport } from './routes/_authed.$wid.monitors.new'
import { Route as AuthedWidMonitorsMidRouteImport } from './routes/_authed.$wid.monitors.$mid'
import { Route as AuthedWidLogsProjectRouteImport } from './routes/_authed.$wid.logs.$project'
import { Route as AuthedWidAdminWorkersRouteImport } from './routes/_authed.$wid.admin.workers'
import { Route as AuthedWidAdminLogBucketsRouteImport } from './routes/_authed.$wid.admin.log-buckets'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SRoute = SRouteImport.update({
  id: '/s',
  path: '/s',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentsRoute = IncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SSlugRoute = SSlugRouteImport.update({
  id: '/s_/$slug',
  path: '/s/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedWidRoute = AuthedWidRouteImport.update({
  id: '/$wid',
  path: '/$wid',
  getParentRoute: () => AuthedRoute,
} as any)
const SSlugIndexRoute = SSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SSlugRoute,
} as any)
const AuthedWidIndexRoute = AuthedWidIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedWidRoute,
} as any)
const SSlugIncidentsRoute = SSlugIncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => SSlugRoute,
} as any)
const AuthedWidStatusRoute = AuthedWidStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => AuthedWidRoute,
} as any)
const AuthedWidSettingsRoute = AuthedWidSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedWidRoute,
} as any)
const AuthedWidMembersRoute = AuthedWidMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AuthedWidRoute,
} as any)
const AuthedWidIncidentsRoute = AuthedWidIncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => AuthedWidRoute,
} as any)
const AuthedWidSettingsIndexRoute = AuthedWidSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedWidSettingsRoute,
} as any)
const AuthedWidMonitorsIndexRoute = AuthedWidMonitorsIndexRouteImport.update({
  id: '/monitors/',
  path: '/monitors/',
  getParentRoute: () => AuthedWidRoute,
} as any)
const AuthedWidLogsIndexRoute = AuthedWidLogsIndexRouteImport.update({
  id: '/logs/',
  path: '/logs/',
  getParentRoute: () => AuthedWidRoute,
} as any)
const AuthedWidSettingsWorkersRoute =
  AuthedWidSettingsWorkersRouteImport.update({
    id: '/workers',
    path: '/workers',
    getParentRoute: () => AuthedWidSettingsRoute,
  } as any)
const AuthedWidSettingsNotificationsRoute =
  AuthedWidSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthedWidSettingsRoute,
  } as any)
const AuthedWidSettingsMembersRoute =
  AuthedWidSettingsMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AuthedWidSettingsRoute,
  } as any)
const AuthedWidSettingsLogStorageRoute =
  AuthedWidSettingsLogStorageRouteImport.update({
    id: '/log-storage',
    path: '/log-storage',
    getParentRoute: () => AuthedWidSettingsRoute,
  } as any)
const AuthedWidSettingsBillingRoute =
  AuthedWidSettingsBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => AuthedWidSettingsRoute,
  } as any)
const AuthedWidMonitorsNewRoute = AuthedWidMonitorsNewRouteImport.update({
  id: '/monitors/new',
  path: '/monitors/new',
  getParentRoute: () => AuthedWidRoute,
} as any)
const AuthedWidMonitorsMidRoute = AuthedWidMonitorsMidRouteImport.update({
  id: '/monitors/$mid',
  path: '/monitors/$mid',
  getParentRoute: () => AuthedWidRoute,
} as any)
const AuthedWidLogsProjectRoute = AuthedWidLogsProjectRouteImport.update({
  id: '/logs/$project',
  path: '/logs/$project',
  getParentRoute: () => AuthedWidRoute,
} as any)
const AuthedWidAdminWorkersRoute = AuthedWidAdminWorkersRouteImport.update({
  id: '/admin/workers',
  path: '/admin/workers',
  getParentRoute: () => AuthedWidRoute,
} as any)
const AuthedWidAdminLogBucketsRoute =
  AuthedWidAdminLogBucketsRouteImport.update({
    id: '/admin/log-buckets',
    path: '/admin/log-buckets',
    getParentRoute: () => AuthedWidRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/incidents': typeof IncidentsRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/s': typeof SRoute
  '/signup': typeof SignupRoute
  '/$wid': typeof AuthedWidRouteWithChildren
  '/invite/$token': typeof InviteTokenRoute
  '/s/$slug': typeof SSlugRouteWithChildren
  '/$wid/incidents': typeof AuthedWidIncidentsRoute
  '/$wid/members': typeof AuthedWidMembersRoute
  '/$wid/settings': typeof AuthedWidSettingsRouteWithChildren
  '/$wid/status': typeof AuthedWidStatusRoute
  '/s/$slug/incidents': typeof SSlugIncidentsRoute
  '/$wid/': typeof AuthedWidIndexRoute
  '/s/$slug/': typeof SSlugIndexRoute
  '/$wid/admin/log-buckets': typeof AuthedWidAdminLogBucketsRoute
  '/$wid/admin/workers': typeof AuthedWidAdminWorkersRoute
  '/$wid/logs/$project': typeof AuthedWidLogsProjectRoute
  '/$wid/monitors/$mid': typeof AuthedWidMonitorsMidRoute
  '/$wid/monitors/new': typeof AuthedWidMonitorsNewRoute
  '/$wid/settings/billing': typeof AuthedWidSettingsBillingRoute
  '/$wid/settings/log-storage': typeof AuthedWidSettingsLogStorageRoute
  '/$wid/settings/members': typeof AuthedWidSettingsMembersRoute
  '/$wid/settings/notifications': typeof AuthedWidSettingsNotificationsRoute
  '/$wid/settings/workers': typeof AuthedWidSettingsWorkersRoute
  '/$wid/logs/': typeof AuthedWidLogsIndexRoute
  '/$wid/monitors/': typeof AuthedWidMonitorsIndexRoute
  '/$wid/settings/': typeof AuthedWidSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/incidents': typeof IncidentsRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/s': typeof SRoute
  '/signup': typeof SignupRoute
  '/invite/$token': typeof InviteTokenRoute
  '/$wid/incidents': typeof AuthedWidIncidentsRoute
  '/$wid/members': typeof AuthedWidMembersRoute
  '/$wid/status': typeof AuthedWidStatusRoute
  '/s/$slug/incidents': typeof SSlugIncidentsRoute
  '/$wid': typeof AuthedWidIndexRoute
  '/s/$slug': typeof SSlugIndexRoute
  '/$wid/admin/log-buckets': typeof AuthedWidAdminLogBucketsRoute
  '/$wid/admin/workers': typeof AuthedWidAdminWorkersRoute
  '/$wid/logs/$project': typeof AuthedWidLogsProjectRoute
  '/$wid/monitors/$mid': typeof AuthedWidMonitorsMidRoute
  '/$wid/monitors/new': typeof AuthedWidMonitorsNewRoute
  '/$wid/settings/billing': typeof AuthedWidSettingsBillingRoute
  '/$wid/settings/log-storage': typeof AuthedWidSettingsLogStorageRoute
  '/$wid/settings/members': typeof AuthedWidSettingsMembersRoute
  '/$wid/settings/notifications': typeof AuthedWidSettingsNotificationsRoute
  '/$wid/settings/workers': typeof AuthedWidSettingsWorkersRoute
  '/$wid/logs': typeof AuthedWidLogsIndexRoute
  '/$wid/monitors': typeof AuthedWidMonitorsIndexRoute
  '/$wid/settings': typeof AuthedWidSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/incidents': typeof IncidentsRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/s': typeof SRoute
  '/signup': typeof SignupRoute
  '/_authed/$wid': typeof AuthedWidRouteWithChildren
  '/invite/$token': typeof InviteTokenRoute
  '/s_/$slug': typeof SSlugRouteWithChildren
  '/_authed/$wid/incidents': typeof AuthedWidIncidentsRoute
  '/_authed/$wid/members': typeof AuthedWidMembersRoute
  '/_authed/$wid/settings': typeof AuthedWidSettingsRouteWithChildren
  '/_authed/$wid/status': typeof AuthedWidStatusRoute
  '/s_/$slug/incidents': typeof SSlugIncidentsRoute
  '/_authed/$wid/': typeof AuthedWidIndexRoute
  '/s_/$slug/': typeof SSlugIndexRoute
  '/_authed/$wid/admin/log-buckets': typeof AuthedWidAdminLogBucketsRoute
  '/_authed/$wid/admin/workers': typeof AuthedWidAdminWorkersRoute
  '/_authed/$wid/logs/$project': typeof AuthedWidLogsProjectRoute
  '/_authed/$wid/monitors/$mid': typeof AuthedWidMonitorsMidRoute
  '/_authed/$wid/monitors/new': typeof AuthedWidMonitorsNewRoute
  '/_authed/$wid/settings/billing': typeof AuthedWidSettingsBillingRoute
  '/_authed/$wid/settings/log-storage': typeof AuthedWidSettingsLogStorageRoute
  '/_authed/$wid/settings/members': typeof AuthedWidSettingsMembersRoute
  '/_authed/$wid/settings/notifications': typeof AuthedWidSettingsNotificationsRoute
  '/_authed/$wid/settings/workers': typeof AuthedWidSettingsWorkersRoute
  '/_authed/$wid/logs/': typeof AuthedWidLogsIndexRoute
  '/_authed/$wid/monitors/': typeof AuthedWidMonitorsIndexRoute
  '/_authed/$wid/settings/': typeof AuthedWidSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/incidents'
    | '/login'
    | '/pricing'
    | '/s'
    | '/signup'
    | '/$wid'
    | '/invite/$token'
    | '/s/$slug'
    | '/$wid/incidents'
    | '/$wid/members'
    | '/$wid/settings'
    | '/$wid/status'
    | '/s/$slug/incidents'
    | '/$wid/'
    | '/s/$slug/'
    | '/$wid/admin/log-buckets'
    | '/$wid/admin/workers'
    | '/$wid/logs/$project'
    | '/$wid/monitors/$mid'
    | '/$wid/monitors/new'
    | '/$wid/settings/billing'
    | '/$wid/settings/log-storage'
    | '/$wid/settings/members'
    | '/$wid/settings/notifications'
    | '/$wid/settings/workers'
    | '/$wid/logs/'
    | '/$wid/monitors/'
    | '/$wid/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/incidents'
    | '/login'
    | '/pricing'
    | '/s'
    | '/signup'
    | '/invite/$token'
    | '/$wid/incidents'
    | '/$wid/members'
    | '/$wid/status'
    | '/s/$slug/incidents'
    | '/$wid'
    | '/s/$slug'
    | '/$wid/admin/log-buckets'
    | '/$wid/admin/workers'
    | '/$wid/logs/$project'
    | '/$wid/monitors/$mid'
    | '/$wid/monitors/new'
    | '/$wid/settings/billing'
    | '/$wid/settings/log-storage'
    | '/$wid/settings/members'
    | '/$wid/settings/notifications'
    | '/$wid/settings/workers'
    | '/$wid/logs'
    | '/$wid/monitors'
    | '/$wid/settings'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/incidents'
    | '/login'
    | '/pricing'
    | '/s'
    | '/signup'
    | '/_authed/$wid'
    | '/invite/$token'
    | '/s_/$slug'
    | '/_authed/$wid/incidents'
    | '/_authed/$wid/members'
    | '/_authed/$wid/settings'
    | '/_authed/$wid/status'
    | '/s_/$slug/incidents'
    | '/_authed/$wid/'
    | '/s_/$slug/'
    | '/_authed/$wid/admin/log-buckets'
    | '/_authed/$wid/admin/workers'
    | '/_authed/$wid/logs/$project'
    | '/_authed/$wid/monitors/$mid'
    | '/_authed/$wid/monitors/new'
    | '/_authed/$wid/settings/billing'
    | '/_authed/$wid/settings/log-storage'
    | '/_authed/$wid/settings/members'
    | '/_authed/$wid/settings/notifications'
    | '/_authed/$wid/settings/workers'
    | '/_authed/$wid/logs/'
    | '/_authed/$wid/monitors/'
    | '/_authed/$wid/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  IncidentsRoute: typeof IncidentsRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  SRoute: typeof SRoute
  SignupRoute: typeof SignupRoute
  InviteTokenRoute: typeof InviteTokenRoute
  SSlugRoute: typeof SSlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s': {
      id: '/s'
      path: '/s'
      fullPath: '/s'
      preLoaderRoute: typeof SRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidents': {
      id: '/incidents'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof IncidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s_/$slug': {
      id: '/s_/$slug'
      path: '/s/$slug'
      fullPath: '/s/$slug'
      preLoaderRoute: typeof SSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/$wid': {
      id: '/_authed/$wid'
      path: '/$wid'
      fullPath: '/$wid'
      preLoaderRoute: typeof AuthedWidRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/s_/$slug/': {
      id: '/s_/$slug/'
      path: '/'
      fullPath: '/s/$slug/'
      preLoaderRoute: typeof SSlugIndexRouteImport
      parentRoute: typeof SSlugRoute
    }
    '/_authed/$wid/': {
      id: '/_authed/$wid/'
      path: '/'
      fullPath: '/$wid/'
      preLoaderRoute: typeof AuthedWidIndexRouteImport
      parentRoute: typeof AuthedWidRoute
    }
    '/s_/$slug/incidents': {
      id: '/s_/$slug/incidents'
      path: '/incidents'
      fullPath: '/s/$slug/incidents'
      preLoaderRoute: typeof SSlugIncidentsRouteImport
      parentRoute: typeof SSlugRoute
    }
    '/_authed/$wid/status': {
      id: '/_authed/$wid/status'
      path: '/status'
      fullPath: '/$wid/status'
      preLoaderRoute: typeof AuthedWidStatusRouteImport
      parentRoute: typeof AuthedWidRoute
    }
    '/_authed/$wid/settings': {
      id: '/_authed/$wid/settings'
      path: '/settings'
      fullPath: '/$wid/settings'
      preLoaderRoute: typeof AuthedWidSettingsRouteImport
      parentRoute: typeof AuthedWidRoute
    }
    '/_authed/$wid/members': {
      id: '/_authed/$wid/members'
      path: '/members'
      fullPath: '/$wid/members'
      preLoaderRoute: typeof AuthedWidMembersRouteImport
      parentRoute: typeof AuthedWidRoute
    }
    '/_authed/$wid/incidents': {
      id: '/_authed/$wid/incidents'
      path: '/incidents'
      fullPath: '/$wid/incidents'
      preLoaderRoute: typeof AuthedWidIncidentsRouteImport
      parentRoute: typeof AuthedWidRoute
    }
    '/_authed/$wid/settings/': {
      id: '/_authed/$wid/settings/'
      path: '/'
      fullPath: '/$wid/settings/'
      preLoaderRoute: typeof AuthedWidSettingsIndexRouteImport
      parentRoute: typeof AuthedWidSettingsRoute
    }
    '/_authed/$wid/monitors/': {
      id: '/_authed/$wid/monitors/'
      path: '/monitors'
      fullPath: '/$wid/monitors/'
      preLoaderRoute: typeof AuthedWidMonitorsIndexRouteImport
      parentRoute: typeof AuthedWidRoute
    }
    '/_authed/$wid/logs/': {
      id: '/_authed/$wid/logs/'
      path: '/logs'
      fullPath: '/$wid/logs/'
      preLoaderRoute: typeof AuthedWidLogsIndexRouteImport
      parentRoute: typeof AuthedWidRoute
    }
    '/_authed/$wid/settings/workers': {
      id: '/_authed/$wid/settings/workers'
      path: '/workers'
      fullPath: '/$wid/settings/workers'
      preLoaderRoute: typeof AuthedWidSettingsWorkersRouteImport
      parentRoute: typeof AuthedWidSettingsRoute
    }
    '/_authed/$wid/settings/notifications': {
      id: '/_authed/$wid/settings/notifications'
      path: '/notifications'
      fullPath: '/$wid/settings/notifications'
      preLoaderRoute: typeof AuthedWidSettingsNotificationsRouteImport
      parentRoute: typeof AuthedWidSettingsRoute
    }
    '/_authed/$wid/settings/members': {
      id: '/_authed/$wid/settings/members'
      path: '/members'
      fullPath: '/$wid/settings/members'
      preLoaderRoute: typeof AuthedWidSettingsMembersRouteImport
      parentRoute: typeof AuthedWidSettingsRoute
    }
    '/_authed/$wid/settings/log-storage': {
      id: '/_authed/$wid/settings/log-storage'
      path: '/log-storage'
      fullPath: '/$wid/settings/log-storage'
      preLoaderRoute: typeof AuthedWidSettingsLogStorageRouteImport
      parentRoute: typeof AuthedWidSettingsRoute
    }
    '/_authed/$wid/settings/billing': {
      id: '/_authed/$wid/settings/billing'
      path: '/billing'
      fullPath: '/$wid/settings/billing'
      preLoaderRoute: typeof AuthedWidSettingsBillingRouteImport
      parentRoute: typeof AuthedWidSettingsRoute
    }
    '/_authed/$wid/monitors/new': {
      id: '/_authed/$wid/monitors/new'
      path: '/monitors/new'
      fullPath: '/$wid/monitors/new'
      preLoaderRoute: typeof AuthedWidMonitorsNewRouteImport
      parentRoute: typeof AuthedWidRoute
    }
    '/_authed/$wid/monitors/$mid': {
      id: '/_authed/$wid/monitors/$mid'
      path: '/monitors/$mid'
      fullPath: '/$wid/monitors/$mid'
      preLoaderRoute: typeof AuthedWidMonitorsMidRouteImport
      parentRoute: typeof AuthedWidRoute
    }
    '/_authed/$wid/logs/$project': {
      id: '/_authed/$wid/logs/$project'
      path: '/logs/$project'
      fullPath: '/$wid/logs/$project'
      preLoaderRoute: typeof AuthedWidLogsProjectRouteImport
      parentRoute: typeof AuthedWidRoute
    }
    '/_authed/$wid/admin/workers': {
      id: '/_authed/$wid/admin/workers'
      path: '/admin/workers'
      fullPath: '/$wid/admin/workers'
      preLoaderRoute: typeof AuthedWidAdminWorkersRouteImport
      parentRoute: typeof AuthedWidRoute
    }
    '/_authed/$wid/admin/log-buckets': {
      id: '/_authed/$wid/admin/log-buckets'
      path: '/admin/log-buckets'
      fullPath: '/$wid/admin/log-buckets'
      preLoaderRoute: typeof AuthedWidAdminLogBucketsRouteImport
      parentRoute: typeof AuthedWidRoute
    }
  }
}

interface AuthedWidSettingsRouteChildren {
  AuthedWidSettingsBillingRoute: typeof AuthedWidSettingsBillingRoute
  AuthedWidSettingsLogStorageRoute: typeof AuthedWidSettingsLogStorageRoute
  AuthedWidSettingsMembersRoute: typeof AuthedWidSettingsMembersRoute
  AuthedWidSettingsNotificationsRoute: typeof AuthedWidSettingsNotificationsRoute
  AuthedWidSettingsWorkersRoute: typeof AuthedWidSettingsWorkersRoute
  AuthedWidSettingsIndexRoute: typeof AuthedWidSettingsIndexRoute
}

const AuthedWidSettingsRouteChildren: AuthedWidSettingsRouteChildren = {
  AuthedWidSettingsBillingRoute: AuthedWidSettingsBillingRoute,
  AuthedWidSettingsLogStorageRoute: AuthedWidSettingsLogStorageRoute,
  AuthedWidSettingsMembersRoute: AuthedWidSettingsMembersRoute,
  AuthedWidSettingsNotificationsRoute: AuthedWidSettingsNotificationsRoute,
  AuthedWidSettingsWorkersRoute: AuthedWidSettingsWorkersRoute,
  AuthedWidSettingsIndexRoute: AuthedWidSettingsIndexRoute,
}

const AuthedWidSettingsRouteWithChildren =
  AuthedWidSettingsRoute._addFileChildren(AuthedWidSettingsRouteChildren)

interface AuthedWidRouteChildren {
  AuthedWidIncidentsRoute: typeof AuthedWidIncidentsRoute
  AuthedWidMembersRoute: typeof AuthedWidMembersRoute
  AuthedWidSettingsRoute: typeof AuthedWidSettingsRouteWithChildren
  AuthedWidStatusRoute: typeof AuthedWidStatusRoute
  AuthedWidIndexRoute: typeof AuthedWidIndexRoute
  AuthedWidAdminLogBucketsRoute: typeof AuthedWidAdminLogBucketsRoute
  AuthedWidAdminWorkersRoute: typeof AuthedWidAdminWorkersRoute
  AuthedWidLogsProjectRoute: typeof AuthedWidLogsProjectRoute
  AuthedWidMonitorsMidRoute: typeof AuthedWidMonitorsMidRoute
  AuthedWidMonitorsNewRoute: typeof AuthedWidMonitorsNewRoute
  AuthedWidLogsIndexRoute: typeof AuthedWidLogsIndexRoute
  AuthedWidMonitorsIndexRoute: typeof AuthedWidMonitorsIndexRoute
}

const AuthedWidRouteChildren: AuthedWidRouteChildren = {
  AuthedWidIncidentsRoute: AuthedWidIncidentsRoute,
  AuthedWidMembersRoute: AuthedWidMembersRoute,
  AuthedWidSettingsRoute: AuthedWidSettingsRouteWithChildren,
  AuthedWidStatusRoute: AuthedWidStatusRoute,
  AuthedWidIndexRoute: AuthedWidIndexRoute,
  AuthedWidAdminLogBucketsRoute: AuthedWidAdminLogBucketsRoute,
  AuthedWidAdminWorkersRoute: AuthedWidAdminWorkersRoute,
  AuthedWidLogsProjectRoute: AuthedWidLogsProjectRoute,
  AuthedWidMonitorsMidRoute: AuthedWidMonitorsMidRoute,
  AuthedWidMonitorsNewRoute: AuthedWidMonitorsNewRoute,
  AuthedWidLogsIndexRoute: AuthedWidLogsIndexRoute,
  AuthedWidMonitorsIndexRoute: AuthedWidMonitorsIndexRoute,
}

const AuthedWidRouteWithChildren = AuthedWidRoute._addFileChildren(
  AuthedWidRouteChildren,
)

interface AuthedRouteChildren {
  AuthedWidRoute: typeof AuthedWidRouteWithChildren
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedWidRoute: AuthedWidRouteWithChildren,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

interface SSlugRouteChildren {
  SSlugIncidentsRoute: typeof SSlugIncidentsRoute
  SSlugIndexRoute: typeof SSlugIndexRoute
}

const SSlugRouteChildren: SSlugRouteChildren = {
  SSlugIncidentsRoute: SSlugIncidentsRoute,
  SSlugIndexRoute: SSlugIndexRoute,
}

const SSlugRouteWithChildren = SSlugRoute._addFileChildren(SSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  IncidentsRoute: IncidentsRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  SRoute: SRoute,
  SignupRoute: SignupRoute,
  InviteTokenRoute: InviteTokenRoute,
  SSlugRoute: SSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
