/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SlackLinkRouteImport } from './routes/slack.link'
import { Route as OauthAuthorizeRouteImport } from './routes/oauth.authorize'
import { Route as LegalTypeRouteImport } from './routes/legal.$type'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as DiscordLinkRouteImport } from './routes/discord.link'
import { Route as AppWorkspaceRouteImport } from './routes/_app.workspace'
import { Route as AppProjectsRouteImport } from './routes/_app.projects'
import { Route as AppLabelsRouteImport } from './routes/_app.labels'
import { Route as AppIssuesRouteImport } from './routes/_app.issues'
import { Route as AppInboxRouteImport } from './routes/_app.inbox'
import { Route as AppFavoritesRouteImport } from './routes/_app.favorites'
import { Route as AppChatsRouteImport } from './routes/_app.chats'
import { Route as AppChatRouteImport } from './routes/_app.chat'
import { Route as AppAccountRouteImport } from './routes/_app.account'
import { Route as AppWorkspaceSettingsRouteImport } from './routes/_app.workspace.settings'
import { Route as AppProjectsProjectIdRouteImport } from './routes/_app.projects.$projectId'
import { Route as AppMembersMemberIdRouteImport } from './routes/_app.members.$memberId'
import { Route as AppIssuesIssueIdRouteImport } from './routes/_app.issues.$issueId'
import { Route as AppChatChatIdRouteImport } from './routes/_app.chat.$chatId'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlackLinkRoute = SlackLinkRouteImport.update({
  id: '/slack/link',
  path: '/slack/link',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthAuthorizeRoute = OauthAuthorizeRouteImport.update({
  id: '/oauth/authorize',
  path: '/oauth/authorize',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTypeRoute = LegalTypeRouteImport.update({
  id: '/$type',
  path: '/$type',
  getParentRoute: () => LegalRoute,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscordLinkRoute = DiscordLinkRouteImport.update({
  id: '/discord/link',
  path: '/discord/link',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkspaceRoute = AppWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppLabelsRoute = AppLabelsRouteImport.update({
  id: '/labels',
  path: '/labels',
  getParentRoute: () => AppRoute,
} as any)
const AppIssuesRoute = AppIssuesRouteImport.update({
  id: '/issues',
  path: '/issues',
  getParentRoute: () => AppRoute,
} as any)
const AppInboxRoute = AppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppRoute,
} as any)
const AppFavoritesRoute = AppFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => AppRoute,
} as any)
const AppChatsRoute = AppChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkspaceSettingsRoute = AppWorkspaceSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppWorkspaceRoute,
} as any)
const AppProjectsProjectIdRoute = AppProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => AppProjectsRoute,
} as any)
const AppMembersMemberIdRoute = AppMembersMemberIdRouteImport.update({
  id: '/members/$memberId',
  path: '/members/$memberId',
  getParentRoute: () => AppRoute,
} as any)
const AppIssuesIssueIdRoute = AppIssuesIssueIdRouteImport.update({
  id: '/$issueId',
  path: '/$issueId',
  getParentRoute: () => AppIssuesRoute,
} as any)
const AppChatChatIdRoute = AppChatChatIdRouteImport.update({
  id: '/$chatId',
  path: '/$chatId',
  getParentRoute: () => AppChatRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/legal': typeof LegalRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/account': typeof AppAccountRoute
  '/chat': typeof AppChatRouteWithChildren
  '/chats': typeof AppChatsRoute
  '/favorites': typeof AppFavoritesRoute
  '/inbox': typeof AppInboxRoute
  '/issues': typeof AppIssuesRouteWithChildren
  '/labels': typeof AppLabelsRoute
  '/projects': typeof AppProjectsRouteWithChildren
  '/workspace': typeof AppWorkspaceRouteWithChildren
  '/discord/link': typeof DiscordLinkRoute
  '/invite/$token': typeof InviteTokenRoute
  '/legal/$type': typeof LegalTypeRoute
  '/oauth/authorize': typeof OauthAuthorizeRoute
  '/slack/link': typeof SlackLinkRoute
  '/chat/$chatId': typeof AppChatChatIdRoute
  '/issues/$issueId': typeof AppIssuesIssueIdRoute
  '/members/$memberId': typeof AppMembersMemberIdRoute
  '/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/workspace/settings': typeof AppWorkspaceSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/legal': typeof LegalRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/account': typeof AppAccountRoute
  '/chat': typeof AppChatRouteWithChildren
  '/chats': typeof AppChatsRoute
  '/favorites': typeof AppFavoritesRoute
  '/inbox': typeof AppInboxRoute
  '/issues': typeof AppIssuesRouteWithChildren
  '/labels': typeof AppLabelsRoute
  '/projects': typeof AppProjectsRouteWithChildren
  '/workspace': typeof AppWorkspaceRouteWithChildren
  '/discord/link': typeof DiscordLinkRoute
  '/invite/$token': typeof InviteTokenRoute
  '/legal/$type': typeof LegalTypeRoute
  '/oauth/authorize': typeof OauthAuthorizeRoute
  '/slack/link': typeof SlackLinkRoute
  '/chat/$chatId': typeof AppChatChatIdRoute
  '/issues/$issueId': typeof AppIssuesIssueIdRoute
  '/members/$memberId': typeof AppMembersMemberIdRoute
  '/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/workspace/settings': typeof AppWorkspaceSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/legal': typeof LegalRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_app/account': typeof AppAccountRoute
  '/_app/chat': typeof AppChatRouteWithChildren
  '/_app/chats': typeof AppChatsRoute
  '/_app/favorites': typeof AppFavoritesRoute
  '/_app/inbox': typeof AppInboxRoute
  '/_app/issues': typeof AppIssuesRouteWithChildren
  '/_app/labels': typeof AppLabelsRoute
  '/_app/projects': typeof AppProjectsRouteWithChildren
  '/_app/workspace': typeof AppWorkspaceRouteWithChildren
  '/discord/link': typeof DiscordLinkRoute
  '/invite/$token': typeof InviteTokenRoute
  '/legal/$type': typeof LegalTypeRoute
  '/oauth/authorize': typeof OauthAuthorizeRoute
  '/slack/link': typeof SlackLinkRoute
  '/_app/chat/$chatId': typeof AppChatChatIdRoute
  '/_app/issues/$issueId': typeof AppIssuesIssueIdRoute
  '/_app/members/$memberId': typeof AppMembersMemberIdRoute
  '/_app/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/_app/workspace/settings': typeof AppWorkspaceSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/legal'
    | '/login'
    | '/reset-password'
    | '/verify-email'
    | '/account'
    | '/chat'
    | '/chats'
    | '/favorites'
    | '/inbox'
    | '/issues'
    | '/labels'
    | '/projects'
    | '/workspace'
    | '/discord/link'
    | '/invite/$token'
    | '/legal/$type'
    | '/oauth/authorize'
    | '/slack/link'
    | '/chat/$chatId'
    | '/issues/$issueId'
    | '/members/$memberId'
    | '/projects/$projectId'
    | '/workspace/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/legal'
    | '/login'
    | '/reset-password'
    | '/verify-email'
    | '/account'
    | '/chat'
    | '/chats'
    | '/favorites'
    | '/inbox'
    | '/issues'
    | '/labels'
    | '/projects'
    | '/workspace'
    | '/discord/link'
    | '/invite/$token'
    | '/legal/$type'
    | '/oauth/authorize'
    | '/slack/link'
    | '/chat/$chatId'
    | '/issues/$issueId'
    | '/members/$memberId'
    | '/projects/$projectId'
    | '/workspace/settings'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/legal'
    | '/login'
    | '/reset-password'
    | '/verify-email'
    | '/_app/account'
    | '/_app/chat'
    | '/_app/chats'
    | '/_app/favorites'
    | '/_app/inbox'
    | '/_app/issues'
    | '/_app/labels'
    | '/_app/projects'
    | '/_app/workspace'
    | '/discord/link'
    | '/invite/$token'
    | '/legal/$type'
    | '/oauth/authorize'
    | '/slack/link'
    | '/_app/chat/$chatId'
    | '/_app/issues/$issueId'
    | '/_app/members/$memberId'
    | '/_app/projects/$projectId'
    | '/_app/workspace/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LegalRoute: typeof LegalRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  DiscordLinkRoute: typeof DiscordLinkRoute
  InviteTokenRoute: typeof InviteTokenRoute
  OauthAuthorizeRoute: typeof OauthAuthorizeRoute
  SlackLinkRoute: typeof SlackLinkRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slack/link': {
      id: '/slack/link'
      path: '/slack/link'
      fullPath: '/slack/link'
      preLoaderRoute: typeof SlackLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/authorize': {
      id: '/oauth/authorize'
      path: '/oauth/authorize'
      fullPath: '/oauth/authorize'
      preLoaderRoute: typeof OauthAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/$type': {
      id: '/legal/$type'
      path: '/$type'
      fullPath: '/legal/$type'
      preLoaderRoute: typeof LegalTypeRouteImport
      parentRoute: typeof LegalRoute
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discord/link': {
      id: '/discord/link'
      path: '/discord/link'
      fullPath: '/discord/link'
      preLoaderRoute: typeof DiscordLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/workspace': {
      id: '/_app/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof AppWorkspaceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects': {
      id: '/_app/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/labels': {
      id: '/_app/labels'
      path: '/labels'
      fullPath: '/labels'
      preLoaderRoute: typeof AppLabelsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/issues': {
      id: '/_app/issues'
      path: '/issues'
      fullPath: '/issues'
      preLoaderRoute: typeof AppIssuesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inbox': {
      id: '/_app/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AppInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/favorites': {
      id: '/_app/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof AppFavoritesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chats': {
      id: '/_app/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof AppChatsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat': {
      id: '/_app/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/account': {
      id: '/_app/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workspace/settings': {
      id: '/_app/workspace/settings'
      path: '/settings'
      fullPath: '/workspace/settings'
      preLoaderRoute: typeof AppWorkspaceSettingsRouteImport
      parentRoute: typeof AppWorkspaceRoute
    }
    '/_app/projects/$projectId': {
      id: '/_app/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AppProjectsProjectIdRouteImport
      parentRoute: typeof AppProjectsRoute
    }
    '/_app/members/$memberId': {
      id: '/_app/members/$memberId'
      path: '/members/$memberId'
      fullPath: '/members/$memberId'
      preLoaderRoute: typeof AppMembersMemberIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/issues/$issueId': {
      id: '/_app/issues/$issueId'
      path: '/$issueId'
      fullPath: '/issues/$issueId'
      preLoaderRoute: typeof AppIssuesIssueIdRouteImport
      parentRoute: typeof AppIssuesRoute
    }
    '/_app/chat/$chatId': {
      id: '/_app/chat/$chatId'
      path: '/$chatId'
      fullPath: '/chat/$chatId'
      preLoaderRoute: typeof AppChatChatIdRouteImport
      parentRoute: typeof AppChatRoute
    }
  }
}

interface AppChatRouteChildren {
  AppChatChatIdRoute: typeof AppChatChatIdRoute
}

const AppChatRouteChildren: AppChatRouteChildren = {
  AppChatChatIdRoute: AppChatChatIdRoute,
}

const AppChatRouteWithChildren =
  AppChatRoute._addFileChildren(AppChatRouteChildren)

interface AppIssuesRouteChildren {
  AppIssuesIssueIdRoute: typeof AppIssuesIssueIdRoute
}

const AppIssuesRouteChildren: AppIssuesRouteChildren = {
  AppIssuesIssueIdRoute: AppIssuesIssueIdRoute,
}

const AppIssuesRouteWithChildren = AppIssuesRoute._addFileChildren(
  AppIssuesRouteChildren,
)

interface AppProjectsRouteChildren {
  AppProjectsProjectIdRoute: typeof AppProjectsProjectIdRoute
}

const AppProjectsRouteChildren: AppProjectsRouteChildren = {
  AppProjectsProjectIdRoute: AppProjectsProjectIdRoute,
}

const AppProjectsRouteWithChildren = AppProjectsRoute._addFileChildren(
  AppProjectsRouteChildren,
)

interface AppWorkspaceRouteChildren {
  AppWorkspaceSettingsRoute: typeof AppWorkspaceSettingsRoute
}

const AppWorkspaceRouteChildren: AppWorkspaceRouteChildren = {
  AppWorkspaceSettingsRoute: AppWorkspaceSettingsRoute,
}

const AppWorkspaceRouteWithChildren = AppWorkspaceRoute._addFileChildren(
  AppWorkspaceRouteChildren,
)

interface AppRouteChildren {
  AppAccountRoute: typeof AppAccountRoute
  AppChatRoute: typeof AppChatRouteWithChildren
  AppChatsRoute: typeof AppChatsRoute
  AppFavoritesRoute: typeof AppFavoritesRoute
  AppInboxRoute: typeof AppInboxRoute
  AppIssuesRoute: typeof AppIssuesRouteWithChildren
  AppLabelsRoute: typeof AppLabelsRoute
  AppProjectsRoute: typeof AppProjectsRouteWithChildren
  AppWorkspaceRoute: typeof AppWorkspaceRouteWithChildren
  AppMembersMemberIdRoute: typeof AppMembersMemberIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountRoute: AppAccountRoute,
  AppChatRoute: AppChatRouteWithChildren,
  AppChatsRoute: AppChatsRoute,
  AppFavoritesRoute: AppFavoritesRoute,
  AppInboxRoute: AppInboxRoute,
  AppIssuesRoute: AppIssuesRouteWithChildren,
  AppLabelsRoute: AppLabelsRoute,
  AppProjectsRoute: AppProjectsRouteWithChildren,
  AppWorkspaceRoute: AppWorkspaceRouteWithChildren,
  AppMembersMemberIdRoute: AppMembersMemberIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface LegalRouteChildren {
  LegalTypeRoute: typeof LegalTypeRoute
}

const LegalRouteChildren: LegalRouteChildren = {
  LegalTypeRoute: LegalTypeRoute,
}

const LegalRouteWithChildren = LegalRoute._addFileChildren(LegalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LegalRoute: LegalRouteWithChildren,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  DiscordLinkRoute: DiscordLinkRoute,
  InviteTokenRoute: InviteTokenRoute,
  OauthAuthorizeRoute: OauthAuthorizeRoute,
  SlackLinkRoute: SlackLinkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
