mod ai;
mod ai_mcp;
mod auth;
mod billing;
mod chats;
mod cors;
mod favorites;
pub mod inbox;
mod invitations;
mod issues;
pub mod labels;
mod mcp_keys;
mod members;
pub mod onboarding;
pub mod preferences;
pub mod projects;
mod realtime;
mod waitlist;

pub use ai::routes as ai_routes;
pub use ai_mcp::routes as ai_mcp_routes;
pub use auth::routes as auth_routes;
pub use billing::routes as billing_routes;
pub use chats::routes as chat_routes;
pub use cors::cors_layer;
pub use favorites::routes as favorite_routes;
pub use inbox::routes as inbox_routes;
pub use invitations::{org_routes as org_invitation_routes, public_routes as invitation_routes};
pub use issues::routes as issue_routes;
pub use labels::routes as label_routes;
pub use mcp_keys::routes as mcp_key_routes;
pub use members::routes as member_routes;
pub use onboarding::routes as onboarding_routes;
pub use preferences::routes as preferences_routes;
pub use projects::routes as project_routes;
pub use realtime::routes as realtime_routes;
pub use waitlist::routes as waitlist_routes;
