mod admin;
mod ai;
mod ai_mcp;
mod auth;
mod billing;
pub(crate) mod chats;
mod cors;
mod dev;
mod discord;
mod favorites;
mod github;
pub(crate) mod inbox;
mod invitations;
pub(crate) mod issue_statuses;
pub(crate) mod issues;
pub(crate) mod labels;
mod mcp_keys;
mod members;
mod notes;
mod oauth;
pub(crate) mod onboarding;
pub(crate) mod preferences;
mod pricing;
pub(crate) mod projects;
mod realtime;
mod roles;
mod security;
mod slack;
mod support;
pub(crate) mod tabs;
mod unsubscribe;
mod waitlist;

pub(crate) use admin::routes as admin_routes;
pub(crate) use ai::routes as ai_routes;
pub(crate) use ai_mcp::routes as ai_mcp_routes;
pub(crate) use auth::routes as auth_routes;
pub(crate) use billing::routes as billing_routes;
pub(crate) use chats::routes as chat_routes;
pub(crate) use cors::cors_layer;
pub(crate) use dev::routes as dev_routes;
pub(crate) use discord::routes as discord_routes;
pub(crate) use favorites::routes as favorite_routes;
pub(crate) use github::{
    routes as github_routes, spawn_auto_importer as spawn_github_auto_importer,
};
pub(crate) use inbox::routes as inbox_routes;
pub(crate) use invitations::{
    org_routes as org_invitation_routes, public_routes as invitation_routes,
};
pub(crate) use issue_statuses::routes as issue_status_routes;
pub(crate) use issues::routes as issue_routes;
pub(crate) use labels::routes as label_routes;
pub(crate) use mcp_keys::routes as mcp_key_routes;
pub(crate) use members::routes as member_routes;
pub(crate) use notes::routes as note_routes;
pub(crate) use oauth::{metadata_routes as oauth_metadata_routes, routes as oauth_routes};
pub(crate) use onboarding::routes as onboarding_routes;
pub(crate) use preferences::routes as preferences_routes;
pub(crate) use pricing::routes as pricing_routes;
pub(crate) use projects::routes as project_routes;
pub(crate) use realtime::routes as realtime_routes;
pub(crate) use roles::routes as role_routes;
pub(crate) use security::routes as security_routes;
pub(crate) use slack::routes as slack_routes;
pub(crate) use support::{admin_routes as support_admin_routes, routes as support_routes};
pub(crate) use tabs::routes as tabs_routes;
pub(crate) use unsubscribe::routes as unsubscribe_routes;
pub(crate) use waitlist::routes as waitlist_routes;
